#!/bin/bash

shiftFirstParameter() {
    shift
    local result="$*"
    echo "$result"
}

export PATH=$PATH:$HOME/bin:$HOME/.local/bin

args=$(shiftFirstParameter "$@")

echo "Argumentos: $args"

# exec jupyter-notebook -- "$args"
exec "$@"
